"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import {
  Binary,
  Bot,
  ClipboardList,
  DatabaseZap,
  Loader2,
  ShieldCheck,
  Workflow,
} from "lucide-react";

import { clinicalApi } from "@/lib/clinical/client";
import type {
  ImagingLaunchResolveResponse,
  ReportRecord,
  StudyWorkspace,
  WorklistRow,
} from "@/lib/clinical/contracts";

const DEMO_USER_ID = "demo-radiologist";
const DEMO_ROLE = "radiologist";

function formatDate(value: string | undefined): string {
  if (!value) {
    return "Unavailable";
  }

  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString();
}

export default function ViewerPage() {
  const searchParams = useSearchParams();
  const launchToken = searchParams.get("launch");

  const [resolvedLaunch, setResolvedLaunch] = useState<ImagingLaunchResolveResponse | null>(
    null,
  );
  const [workspace, setWorkspace] = useState<StudyWorkspace | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [actionMessage, setActionMessage] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [busyAction, setBusyAction] = useState<"report" | "ai" | "derived" | null>(null);
  const [reportId, setReportId] = useState<string | undefined>(undefined);
  const [findingsSummary, setFindingsSummary] = useState("");
  const [impression, setImpression] = useState("");

  useEffect(() => {
    let cancelled = false;

    async function loadViewerWorkspace(activeLaunchToken: string) {
      setLoading(true);
      setError(null);

      try {
        const launch = await clinicalApi.resolveLaunch(activeLaunchToken);
        const nextWorkspace = await clinicalApi.getStudyWorkspace(
          launch.context.studyInstanceUID,
          DEMO_ROLE,
          DEMO_USER_ID,
        );

        if (cancelled) {
          return;
        }

        const latestReport = nextWorkspace.reports[0];
        setResolvedLaunch(launch);
        setWorkspace(nextWorkspace);
        setReportId(latestReport?.reportId);
        setFindingsSummary(latestReport?.findingsSummary ?? "");
        setImpression(latestReport?.impression ?? "");
      } catch (cause) {
        if (!cancelled) {
          setError(
            cause instanceof Error
              ? cause.message
              : "Unable to resolve the clinical launch session.",
          );
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    if (!launchToken) {
      setLoading(false);
      setError("The viewer route requires a launch token generated by the worklist.");
      return () => {
        cancelled = true;
      };
    }

    void loadViewerWorkspace(launchToken);

    return () => {
      cancelled = true;
    };
  }, [launchToken]);

  const refreshWorkspace = async (studyInstanceUID: string) => {
    const nextWorkspace = await clinicalApi.getStudyWorkspace(
      studyInstanceUID,
      DEMO_ROLE,
      DEMO_USER_ID,
    );
    setWorkspace(nextWorkspace);
    return nextWorkspace;
  };

  const handleSaveReport = async (status: "draft" | "final") => {
    if (!resolvedLaunch) {
      return;
    }

    setBusyAction("report");
    setActionMessage(null);
    setActionError(null);

    try {
      const saved = await clinicalApi.saveDraft({
        reportId,
        studyInstanceUID: resolvedLaunch.context.studyInstanceUID,
        status,
        authorUserId: DEMO_USER_ID,
        findingsSummary,
        impression,
      });
      setReportId(saved.reportId);
      setFindingsSummary(saved.findingsSummary);
      setImpression(saved.impression);
      await refreshWorkspace(saved.studyInstanceUID);
      setActionMessage(
        status === "final"
          ? "Report finalized and linked to the study workspace."
          : "Draft report saved to the clinical workspace.",
      );
    } catch (cause) {
      setActionError(cause instanceof Error ? cause.message : "Failed to save report.");
    } finally {
      setBusyAction(null);
    }
  };

  const handleQueueShadowTriage = async () => {
    if (!resolvedLaunch) {
      return;
    }

    setBusyAction("ai");
    setActionMessage(null);
    setActionError(null);

    try {
      await clinicalApi.createAIJob({
        kind: "triage",
        workflowMode: "shadow",
        studyInstanceUID: resolvedLaunch.context.studyInstanceUID,
        modelId: "triage-model",
        modelVersion: "1.0.0",
        inputHash: `study:${resolvedLaunch.context.studyInstanceUID}:shadow`,
        requestedBy: DEMO_USER_ID,
      });
      await refreshWorkspace(resolvedLaunch.context.studyInstanceUID);
      setActionMessage("Shadow triage job queued under the governed backend contract.");
    } catch (cause) {
      setActionError(cause instanceof Error ? cause.message : "Failed to queue AI job.");
    } finally {
      setBusyAction(null);
    }
  };

  const handleStageDerivedResult = async () => {
    if (!resolvedLaunch) {
      return;
    }

    setBusyAction("derived");
    setActionMessage(null);
    setActionError(null);

    try {
      const now = Date.now();
      await clinicalApi.storeDerivedResults({
        actorUserId: DEMO_USER_ID,
        actorRole: DEMO_ROLE,
        objects: [
          {
            objectType: "sr",
            studyInstanceUID: resolvedLaunch.context.studyInstanceUID,
            storageClass: "SR",
            payloadRef: `derived/sr/${resolvedLaunch.context.studyInstanceUID}/${now}`,
            metadata: {
              source: "viewer-host-stub",
              note: "Standards-native placeholder until OHIF-derived object persistence is wired.",
            },
          },
        ],
      });
      await refreshWorkspace(resolvedLaunch.context.studyInstanceUID);
      setActionMessage("Derived result intent persisted through the imaging gateway contract.");
    } catch (cause) {
      setActionError(
        cause instanceof Error ? cause.message : "Failed to persist derived result.",
      );
    } finally {
      setBusyAction(null);
    }
  };

  const worklistRow: WorklistRow | null = workspace?.worklistRow ?? null;
  const latestReport: ReportRecord | null = workspace?.reports[0] ?? null;

  return (
    <div className="min-h-screen overflow-y-auto bg-[#060b16] text-slate-100">
      <div className="mx-auto max-w-7xl px-6 py-10">
        <div className="rounded-3xl border border-cyan-400/20 bg-[linear-gradient(145deg,_rgba(8,15,31,0.98),_rgba(13,23,45,0.96))] p-8 shadow-2xl shadow-cyan-950/20">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 text-xs uppercase tracking-[0.28em] text-cyan-300/80">
                <ShieldCheck className="h-4 w-4" />
                Clinical viewer host
              </div>
              <h1 className="mt-3 text-3xl font-semibold text-white">
                Signed viewer session
              </h1>
              <p className="mt-3 max-w-3xl text-sm text-slate-300">
                This route resolves an opaque launch token, loads the study workspace from the
                clinical API, and keeps report, AI, derived-result, and audit actions inside
                the governed backend boundary until the OHIF surface replaces this host panel.
              </p>
            </div>
            <div className="flex gap-3">
              <Link
                href="/worklist"
                className="rounded-full border border-slate-700 bg-slate-900/60 px-4 py-2 text-sm text-slate-200 transition hover:border-cyan-400/50 hover:text-white"
              >
                Back to worklist
              </Link>
              <Link
                href="/"
                className="rounded-full border border-cyan-300/40 bg-cyan-300/10 px-4 py-2 text-sm text-cyan-200 transition hover:bg-cyan-300/20"
              >
                Research fallback
              </Link>
            </div>
          </div>

          {loading && (
            <div className="mt-8 flex items-center gap-3 rounded-2xl border border-slate-800 bg-slate-950/70 px-4 py-4 text-sm text-slate-300">
              <Loader2 className="h-4 w-4 animate-spin text-cyan-300" />
              Resolving launch token and loading workspace...
            </div>
          )}

          {error && (
            <div className="mt-8 rounded-2xl border border-red-500/40 bg-red-500/10 px-4 py-4 text-sm text-red-200">
              {error}
            </div>
          )}

          {!loading && !error && resolvedLaunch && workspace && (
            <div className="mt-8 grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
              <div className="space-y-6">
                <section className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5">
                  <div className="flex items-center gap-2 text-sm font-medium text-white">
                    <Workflow className="h-4 w-4 text-cyan-300" />
                    Verified launch context
                  </div>
                  <div className="mt-4 grid gap-4 text-sm text-slate-300 md:grid-cols-2">
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Study UID
                      </div>
                      <div className="mt-1 break-all">
                        {resolvedLaunch.context.studyInstanceUID}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Launch token
                      </div>
                      <div className="mt-1 break-all">{resolvedLaunch.launchToken}</div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Patient ref
                      </div>
                      <div className="mt-1">{resolvedLaunch.context.patientRef}</div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Accession
                      </div>
                      <div className="mt-1">
                        {resolvedLaunch.context.accessionNumber ?? "Unavailable"}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Mode
                      </div>
                      <div className="mt-1">{resolvedLaunch.context.mode}</div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        DICOMweb path
                      </div>
                      <div className="mt-1 break-all">{resolvedLaunch.studyWadoRsUri}</div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Signed at
                      </div>
                      <div className="mt-1">{formatDate(resolvedLaunch.context.signedAt)}</div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Expires at
                      </div>
                      <div className="mt-1">{formatDate(resolvedLaunch.context.expiresAt)}</div>
                    </div>
                  </div>
                  <div className="mt-4 text-xs text-slate-500">
                    Granted scopes: {resolvedLaunch.context.scopes.join(", ")}
                  </div>
                </section>

                <section className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5">
                  <div className="flex items-center gap-2 text-sm font-medium text-white">
                    <ClipboardList className="h-4 w-4 text-cyan-300" />
                    Study workspace
                  </div>
                  <div className="mt-4 grid gap-4 text-sm text-slate-300 md:grid-cols-2">
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Description
                      </div>
                      <div className="mt-1">{worklistRow?.description ?? "Unavailable"}</div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Modality
                      </div>
                      <div className="mt-1">{worklistRow?.modality ?? "OT"}</div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Worklist status
                      </div>
                      <div className="mt-1">{worklistRow?.status ?? "new"}</div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Triage score
                      </div>
                      <div className="mt-1">
                        {worklistRow?.triageScore == null
                          ? "Unavailable"
                          : worklistRow.triageScore.toFixed(2)}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Priors
                      </div>
                      <div className="mt-1">
                        {worklistRow?.priorStudyUIDs.length ?? 0} referenced studies
                      </div>
                    </div>
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Last update
                      </div>
                      <div className="mt-1">
                        {formatDate(worklistRow?.lastUpdatedAt)}
                      </div>
                    </div>
                  </div>
                </section>

                <section className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5">
                  <div className="flex items-center gap-2 text-sm font-medium text-white">
                    <DatabaseZap className="h-4 w-4 text-cyan-300" />
                    Reporting workspace
                  </div>
                  <div className="mt-4 grid gap-4">
                    <label className="grid gap-2 text-sm text-slate-300">
                      Findings summary
                      <textarea
                        value={findingsSummary}
                        onChange={(event) => setFindingsSummary(event.target.value)}
                        rows={5}
                        className="rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-sm text-slate-100 outline-none transition focus:border-cyan-400/60"
                        placeholder="Structured findings, key measurements, and prior comparison."
                      />
                    </label>
                    <label className="grid gap-2 text-sm text-slate-300">
                      Impression
                      <textarea
                        value={impression}
                        onChange={(event) => setImpression(event.target.value)}
                        rows={4}
                        className="rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-sm text-slate-100 outline-none transition focus:border-cyan-400/60"
                        placeholder="Concise diagnostic impression with clinician-owned conclusion."
                      />
                    </label>
                    <div className="flex flex-wrap gap-3">
                      <button
                        type="button"
                        onClick={() => void handleSaveReport("draft")}
                        disabled={busyAction === "report"}
                        className="rounded-full bg-cyan-300 px-5 py-3 text-sm font-medium text-slate-950 transition hover:bg-cyan-200 disabled:cursor-wait disabled:opacity-70"
                      >
                        {busyAction === "report" ? "Saving..." : "Save draft"}
                      </button>
                      <button
                        type="button"
                        onClick={() => void handleSaveReport("final")}
                        disabled={busyAction === "report"}
                        className="rounded-full border border-slate-700 bg-slate-900/60 px-5 py-3 text-sm text-slate-100 transition hover:border-cyan-400/40 hover:text-white disabled:cursor-wait disabled:opacity-70"
                      >
                        Finalize report
                      </button>
                    </div>
                    <div className="text-xs text-slate-500">
                      Latest report status: {latestReport?.status ?? "No report yet"}
                    </div>
                  </div>
                </section>
              </div>

              <div className="space-y-6">
                <section className="rounded-2xl border border-cyan-400/20 bg-cyan-400/5 p-5">
                  <div className="flex items-center gap-2 text-sm font-medium text-white">
                    <Bot className="h-4 w-4 text-cyan-300" />
                    Governed assistive actions
                  </div>
                  <p className="mt-3 text-sm text-slate-300">
                    AI remains backend-managed and shadow-first. Derived results are persisted
                    through the DICOMweb contract instead of browser-local state.
                  </p>
                  <div className="mt-4 flex flex-col gap-3">
                    <button
                      type="button"
                      onClick={() => void handleQueueShadowTriage()}
                      disabled={busyAction === "ai"}
                      className="rounded-2xl bg-slate-950/80 px-4 py-3 text-left text-sm text-slate-100 transition hover:border-cyan-400/40 hover:bg-slate-950 disabled:cursor-wait disabled:opacity-70"
                    >
                      {busyAction === "ai" ? "Queueing shadow triage..." : "Queue shadow triage"}
                    </button>
                    <button
                      type="button"
                      onClick={() => void handleStageDerivedResult()}
                      disabled={busyAction === "derived"}
                      className="rounded-2xl bg-slate-950/80 px-4 py-3 text-left text-sm text-slate-100 transition hover:border-cyan-400/40 hover:bg-slate-950 disabled:cursor-wait disabled:opacity-70"
                    >
                      {busyAction === "derived"
                        ? "Persisting derived result..."
                        : "Persist derived SR stub"}
                    </button>
                  </div>
                  {actionMessage && (
                    <div className="mt-4 rounded-2xl border border-emerald-400/30 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-200">
                      {actionMessage}
                    </div>
                  )}
                  {actionError && (
                    <div className="mt-4 rounded-2xl border border-red-500/40 bg-red-500/10 px-4 py-3 text-sm text-red-200">
                      {actionError}
                    </div>
                  )}
                </section>

                <section className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5">
                  <div className="flex items-center gap-2 text-sm font-medium text-white">
                    <Binary className="h-4 w-4 text-cyan-300" />
                    Persisted state
                  </div>
                  <div className="mt-4 space-y-4 text-sm text-slate-300">
                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Reports
                      </div>
                      <div className="mt-2 space-y-2">
                        {workspace.reports.length === 0 && (
                          <div className="rounded-2xl border border-slate-800 bg-slate-950 px-3 py-3 text-slate-400">
                            No persisted report yet.
                          </div>
                        )}
                        {workspace.reports.map((report) => (
                          <div
                            key={report.reportId}
                            className="rounded-2xl border border-slate-800 bg-slate-950 px-3 py-3"
                          >
                            <div className="font-medium text-white">{report.status}</div>
                            <div className="mt-1 text-xs text-slate-500">
                              {report.reportId} · {formatDate(report.updatedAt)}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        AI jobs
                      </div>
                      <div className="mt-2 space-y-2">
                        {workspace.aiJobs.length === 0 && (
                          <div className="rounded-2xl border border-slate-800 bg-slate-950 px-3 py-3 text-slate-400">
                            No governed AI jobs have been queued.
                          </div>
                        )}
                        {workspace.aiJobs.map((job) => (
                          <div
                            key={job.jobId}
                            className="rounded-2xl border border-slate-800 bg-slate-950 px-3 py-3"
                          >
                            <div className="font-medium text-white">
                              {job.kind} · {job.workflowMode}
                            </div>
                            <div className="mt-1 text-xs text-slate-500">
                              {job.jobId} · {job.status} · {formatDate(job.createdAt)}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Derived results
                      </div>
                      <div className="mt-2 space-y-2">
                        {workspace.derivedResults.length === 0 && (
                          <div className="rounded-2xl border border-slate-800 bg-slate-950 px-3 py-3 text-slate-400">
                            No derived DICOM objects persisted yet.
                          </div>
                        )}
                        {workspace.derivedResults.map((result) => (
                          <div
                            key={result.id}
                            className="rounded-2xl border border-slate-800 bg-slate-950 px-3 py-3"
                          >
                            <div className="font-medium text-white">
                              {result.objectType} · {result.storageClass}
                            </div>
                            <div className="mt-1 break-all text-xs text-slate-500">
                              {result.payloadRef ?? result.id}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div>
                      <div className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Audit trail
                      </div>
                      <div className="mt-2 space-y-2">
                        {workspace.audit.length === 0 && (
                          <div className="rounded-2xl border border-slate-800 bg-slate-950 px-3 py-3 text-slate-400">
                            No audit events recorded yet.
                          </div>
                        )}
                        {workspace.audit.slice(0, 6).map((event) => (
                          <div
                            key={event.eventId}
                            className="rounded-2xl border border-slate-800 bg-slate-950 px-3 py-3"
                          >
                            <div className="font-medium text-white">{event.action}</div>
                            <div className="mt-1 text-xs text-slate-500">
                              {event.actorUserId} · {formatDate(event.occurredAt)}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
